# Generated by Django 4.0.3 on 2022-03-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crackdetectionaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crackdetect',
            name='name',
        ),
    ]
