# Generated by Django 4.0.3 on 2022-03-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crackdetectionaapp', '0002_remove_crackdetect_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crackdetect',
            old_name='image',
            new_name='img',
        ),
    ]
