# Generated by Django 4.0.3 on 2022-03-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackdetectionaapp', '0003_rename_image_crackdetect_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crackdetect',
            name='detected_img',
            field=models.ImageField(blank=True, upload_to='result/'),
        ),
    ]
