# Generated by Django 4.0.3 on 2022-04-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackdetectionaapp', '0004_alter_crackdetect_detected_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crackdetect',
            name='detected_img',
            field=models.ImageField(upload_to='result/'),
        ),
    ]
