# Generated by Django 4.0.3 on 2022-05-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackdetectionaapp', '0005_alter_crackdetect_detected_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='crackdetect',
            name='detected_img',
        ),
    ]
